version: "3.8"
services:
  database:
    image: mysql
    container_name: db_docker_symfony
    restart: always
    volumes:
      - db-data:/var/lib/mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    networks:
      - dev
  php:
    build: .
    container_name: php_docker_symfony
    restart: always
    volumes:
      - ./app:/var/www/html
    networks:
      - dev
  apache2:
    image: webdevops/apache:latest
    container_name: apache2_docker_symfony
    ports:
      - "8080:80"
      - "443:443"
    volumes:
      - ./app:/var/www/html
      - ./apache2/vhost.conf:/opt/docker/etc/httpd/vhost.conf
    depends_on:
      - php
      - database
    networks:
      - dev

volumes:
  db-data:

networks:
  dev:
