# syntax=docker/dockerfile:1
FROM php:8.0-apache
RUN apt-get update && apt-get install -y \
    libicu-dev \
    libpq-dev \
    libzip-dev \
    zip \
    unzip \
    git \
    && docker-php-ext-install \
    intl \
    opcache \
    pdo \
    pdo_pgsql \
    zip
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
WORKDIR /var/www/html
COPY composer.json composer.lock symfony.lock ./
RUN composer install --prefer-dist --no-autoloader --no-scripts --no-progress --no-suggest
COPY . ./
RUN composer dump-autoload --optimize --classmap-authoritative
RUN chown -R www-data:www-data var